In [1]:
import numpy as np
from numpy import linalg
from scipy import linalg
from numpy import array

1. (5 баллов) Найти ближайшую ортогональную матрицу (в смысле нормы Фробениуса) к матрице

𝐴 = [[0.5, 2.16506351,  0.4330127], [-0.8660254, 1.25, 0.25], [0, 0.5, 2.5]]
     
Посмотрев на результат, найти соответствующие этому преобразованию угол и направление поворота. Матрицу, угол и направление поворота распечатать в stdout.

In [2]:
A1 = array([[0.5, 2.16506351,  0.4330127], [-0.8660254, 1.25, 0.25], [0, 0.5, 2.5]])

In [3]:
U1, D1, VT1 = linalg.svd(A1)

In [4]:
B = np.dot(U1, VT1)
B

array([[ 5.00000000e-01,  8.66025404e-01, -3.87999535e-10],
       [-8.66025404e-01,  5.00000000e-01,  1.65509444e-11],
       [ 2.08333332e-10,  3.27741901e-10,  1.00000000e+00]])

Анализируя полученную матрицу, можно заметить, что это поворот вокруг оси z на 60 градусов (cosL = 0.5, sinL = 0.866) против часовой стрелки при положительном sinL.

2. (5 баллов) При помощи SVD найти обратную матрицу к квадратной матрице nxn, состоящей из элементов
𝐴ij =1 / (i + j - 1),
для размеров матрицы n=3 и n=10. Результат распечатать в stdout.

In [5]:
Aij3 = []
for i in range(1, 4):    # n=3
    b=[]
    for j in range(1, 4):
        b.append(1/(i+j-1))
    #   b.append('%.2f' % (1/(i+j-1)))
    Aij3.append(b) 
    
for row in Aij3:   #печатаем в виде матрицы
    for elem in row:     
        print(elem, end = ' ')
    print()    

1.0 0.5 0.3333333333333333 
0.5 0.3333333333333333 0.25 
0.3333333333333333 0.25 0.2 


In [6]:
U3, D3, VT3 = linalg.svd(Aij3)

In [7]:
Ainv3 = np.dot(VT3.transpose(),np.dot(np.diag(D3**-1),U3.transpose()))
print(f'Обратная матрица:\n', Ainv3)

Обратная матрица:
 [[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]


In [8]:
Aij10 = []
for i in range(1, 11):    # n=10
    b=[]
    for j in range(1, 11):
        b.append(1/(i+j-1))
    #   b.append('%.2f' % (1/(i+j-1)))
    Aij10.append(b) 
    
for row in Aij10:   #печатаем в виде матрицы
    for elem in row:     
        print(elem, end = ' ')
    print()    

1.0 0.5 0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 
0.5 0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091 
0.3333333333333333 0.25 0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091 0.08333333333333333 
0.25 0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091 0.08333333333333333 0.07692307692307693 
0.2 0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091 0.08333333333333333 0.07692307692307693 0.07142857142857142 
0.16666666666666666 0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091 0.08333333333333333 0.07692307692307693 0.07142857142857142 0.06666666666666667 
0.14285714285714285 0.125 0.1111111111111111 0.1 0.09090909090909091 0.08333333333333333 0.07692307692307693 0.07142857142857142 0.06666666666666667 0.0625 
0.125 0.111111

In [9]:
U10, D10, VT10 = linalg.svd(Aij10)

In [10]:
Ainv10 = np.dot(VT10.transpose(),np.dot(np.diag(D10**-1),U10.transpose()))
print(f'Обратная матрица:\n', Ainv10)

Обратная матрица:
 [[ 9.99977580e+01 -4.94980577e+03  7.91958552e+04 -6.00562267e+05
   2.52233983e+06 -6.30580429e+06  9.60878614e+06 -8.75081307e+06
   4.37538668e+06 -9.23689072e+05]
 [-4.94980503e+03  3.26683118e+05 -5.88023987e+06  4.75642425e+07
  -2.08092254e+08  5.35091561e+08 -8.32360950e+08  7.70072497e+08
  -3.89847910e+08  8.31323094e+07]
 [ 7.91958274e+04 -5.88023884e+06  1.12899818e+08 -9.51280320e+08
   4.28074231e+09 -1.12369066e+10  1.77570308e+10 -1.66335816e+10
   8.50578871e+09 -1.82891580e+09]
 [-6.00561928e+05  4.75642257e+07 -9.51280164e+08  8.24439783e+09
  -3.78725884e+10  1.00993315e+11 -1.61588958e+11  1.52894652e+11
  -7.88361790e+10  1.70699180e+10]
 [ 2.52233788e+06 -2.08092145e+08  4.28074096e+09 -3.78725830e+10
   1.76738399e+11 -4.77192952e+11  7.71219934e+11 -7.35805954e+11
   3.82052721e+11 -8.32159981e+10]
 [-6.30579820e+06  5.35091199e+08 -1.12369016e+10  1.00993287e+11
  -4.77192893e+11  1.30143427e+12 -2.12085459e+12  2.03761750e+12
  -1.06429081e

3. (5 баллов) Для квадратной матрицы nxn, состоящей из элементов
𝐴ij = 𝑖 + 𝑗 − 1,
найти с использованием SVD все решения уравнений AX=0 для n=4 Результат распечатать в stdout.

In [11]:
Aij4 = []
for i in range(1, 5):
    b=[]
    for j in range(1, 5):
        b.append(i+j-1)
    Aij4.append(b) 
    
for row in Aij4:   #печатаем в виде матрицы
    for elem in row:     
        print(elem, end = ' ')
    print()    

1 2 3 4 
2 3 4 5 
3 4 5 6 
4 5 6 7 


In [12]:
def nullspace (A, eps=1e-8):
    U4, D4, VT4 = linalg.svd(A)
    null_sp=np.compress(D4 <= eps, VT4, axis = 0)
    return null_sp.T

In [13]:
nullspace(Aij4)

array([[ 0.30408826, -0.45555497],
       [-0.06590039,  0.83406063],
       [-0.780464  , -0.30145636],
       [ 0.54227613, -0.0770493 ]])

4. (5 баллов) Написать программу, находящую все точки пересечения двух прямых на плоскости методом однородных координат. Прямые заданы уравнениями ax+by+c=0, dx+ey+f=0. Коэффициенты задать константами на ваше усмотрение. Результат распечатать в stdout.

In [14]:
from __future__ import division 

def line(p1, p2):         
    A = (p1[1] - p2[1])
    B = (p2[0] - p1[0])
    C = (p1[0]*p2[1] - p2[0]*p1[1])
    return A, B, -C

def crossing(L1, L2):
    D  = L1[0] * L2[1] - L1[1] * L2[0]
    Dx = L1[2] * L2[1] - L1[1] * L2[2]
    Dy = L1[0] * L2[2] - L1[2] * L2[0]
    if D != 0:
        x = Dx / D
        y = Dy / D
        return x,y
    else:
        return False

In [15]:
L1 = line([0,1], [2,3])
L2 = line([2,3], [0,4])

R = crossing(L1, L2)
if R:
    print(f'Пересечение: ', R)
else:
    print(f'Прямые не пересекаются!')

Пересечение:  (2.0, 3.0)
